//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server
{
    using server.Classi;
    using System;
    using System.Collections.Generic;
    
    public partial class commesso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public commesso()
        {
            this.transazioni = new HashSet<transazioni>();
        }
    
        public long codice_commesso { get; set; }
        public string nome { get; set; }
        public string cognome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transazioni> transazioni { get; set; }

        public void parseCommesso(Commesso login)
        {
            try
            {
                this.codice_commesso = login.codice_commesso;
                this.nome = login.nome;
                this.cognome = login.cognome;
            }
            catch (Exception ex)
            {
                throw new Exception("metodo parseCommesso: " + ex.Message);
            }


        }
    }
}
