//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TecnichedisvilEntities : DbContext
    {
        public TecnichedisvilEntities()
            : base("name=TecnichedisvilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<utenti> utenti { get; set; }
        public virtual DbSet<commesso> commesso { get; set; }
        public virtual DbSet<prodotto> prodotto { get; set; }
        public virtual DbSet<transazioni> transazioni { get; set; }
    }
}
