//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;

    public partial class utenti
    {
        public string cognome { get; set; }
        public string nome { get; set; }
        public Nullable<long> nascita { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string indirizzo { get; set; }
        public Nullable<double> portafoglio { get; set; }
        public int id { get; set; }

        public void parseUtente(Utente login)
        {
            try
            {
                this.email = login.email;
                this.password = login.password;
                this.nome = login.nome;
                this.cognome = login.cognome;
                long datanascita = long.Parse(login.nascita.ToString("yyyyMMdd"));
                this.nascita = datanascita;
                this.indirizzo = login.indirizzo;
                this.portafoglio = login.portafoglio;
                this.id = login.id;
            }
            catch (Exception ex)
            {
                throw new Exception("metodo loginEffettuato: " + ex.Message);
            }


        }
    }
}
