//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server
{
    using System;
    using System.Collections.Generic;
    
    public partial class utenti
    {
        public string cognome { get; set; }
        public string nome { get; set; }
        public Nullable<long> nascita { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string indirizzo { get; set; }
        public Nullable<double> portafoglio { get; set; }
        public int id { get; set; }
    }
}
