//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sito.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utente", Namespace="http://schemas.datacontract.org/2004/07/server")]
    [System.SerializableAttribute()]
    public partial class Utente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string indirizzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime nascitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> portafoglioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.cognomeField, value) != true)) {
                    this.cognomeField = value;
                    this.RaisePropertyChanged("cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                if ((object.ReferenceEquals(this.indirizzoField, value) != true)) {
                    this.indirizzoField = value;
                    this.RaisePropertyChanged("indirizzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime nascita {
            get {
                return this.nascitaField;
            }
            set {
                if ((this.nascitaField.Equals(value) != true)) {
                    this.nascitaField = value;
                    this.RaisePropertyChanged("nascita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> portafoglio {
            get {
                return this.portafoglioField;
            }
            set {
                if ((this.portafoglioField.Equals(value) != true)) {
                    this.portafoglioField = value;
                    this.RaisePropertyChanged("portafoglio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="admin.Esito", Namespace="http://schemas.datacontract.org/2004/07/server")]
    public enum adminEsito : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KO = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commesso", Namespace="http://schemas.datacontract.org/2004/07/server.Classi")]
    [System.SerializableAttribute()]
    public partial class Commesso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long codice_commessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long codice_commesso {
            get {
                return this.codice_commessoField;
            }
            set {
                if ((this.codice_commessoField.Equals(value) != true)) {
                    this.codice_commessoField = value;
                    this.RaisePropertyChanged("codice_commesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.cognomeField, value) != true)) {
                    this.cognomeField = value;
                    this.RaisePropertyChanged("cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prodotto", Namespace="http://schemas.datacontract.org/2004/07/server.Classi")]
    [System.SerializableAttribute()]
    public partial class Prodotto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long codice_prodottoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime data_uscitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double prezzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string producerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantitàField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titoloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long codice_prodotto {
            get {
                return this.codice_prodottoField;
            }
            set {
                if ((this.codice_prodottoField.Equals(value) != true)) {
                    this.codice_prodottoField = value;
                    this.RaisePropertyChanged("codice_prodotto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data_uscita {
            get {
                return this.data_uscitaField;
            }
            set {
                if ((this.data_uscitaField.Equals(value) != true)) {
                    this.data_uscitaField = value;
                    this.RaisePropertyChanged("data_uscita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string genere {
            get {
                return this.genereField;
            }
            set {
                if ((object.ReferenceEquals(this.genereField, value) != true)) {
                    this.genereField = value;
                    this.RaisePropertyChanged("genere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img {
            get {
                return this.imgField;
            }
            set {
                if ((object.ReferenceEquals(this.imgField, value) != true)) {
                    this.imgField = value;
                    this.RaisePropertyChanged("img");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double prezzo {
            get {
                return this.prezzoField;
            }
            set {
                if ((this.prezzoField.Equals(value) != true)) {
                    this.prezzoField = value;
                    this.RaisePropertyChanged("prezzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producer {
            get {
                return this.producerField;
            }
            set {
                if ((object.ReferenceEquals(this.producerField, value) != true)) {
                    this.producerField = value;
                    this.RaisePropertyChanged("producer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantità {
            get {
                return this.quantitàField;
            }
            set {
                if ((this.quantitàField.Equals(value) != true)) {
                    this.quantitàField = value;
                    this.RaisePropertyChanged("quantità");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titolo {
            get {
                return this.titoloField;
            }
            set {
                if ((object.ReferenceEquals(this.titoloField, value) != true)) {
                    this.titoloField = value;
                    this.RaisePropertyChanged("titolo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transazione", Namespace="http://schemas.datacontract.org/2004/07/server.Classi")]
    [System.SerializableAttribute()]
    public partial class Transazione : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long codice_commessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long codice_prodottoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long codice_transazioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double prezzoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long codice_commesso {
            get {
                return this.codice_commessoField;
            }
            set {
                if ((this.codice_commessoField.Equals(value) != true)) {
                    this.codice_commessoField = value;
                    this.RaisePropertyChanged("codice_commesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long codice_prodotto {
            get {
                return this.codice_prodottoField;
            }
            set {
                if ((this.codice_prodottoField.Equals(value) != true)) {
                    this.codice_prodottoField = value;
                    this.RaisePropertyChanged("codice_prodotto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long codice_transazione {
            get {
                return this.codice_transazioneField;
            }
            set {
                if ((this.codice_transazioneField.Equals(value) != true)) {
                    this.codice_transazioneField = value;
                    this.RaisePropertyChanged("codice_transazione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField.Equals(value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double prezzo {
            get {
                return this.prezzoField;
            }
            set {
                if ((this.prezzoField.Equals(value) != true)) {
                    this.prezzoField = value;
                    this.RaisePropertyChanged("prezzo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.Iadmin")]
    public interface Iadmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/DoWork", ReplyAction="http://tempuri.org/Iadmin/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/DoWork", ReplyAction="http://tempuri.org/Iadmin/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/listaUtenti", ReplyAction="http://tempuri.org/Iadmin/listaUtentiResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente[], string> listaUtenti(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/listaUtenti", ReplyAction="http://tempuri.org/Iadmin/listaUtentiResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente[], string>> listaUtentiAsync(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/listaCommessi", ReplyAction="http://tempuri.org/Iadmin/listaCommessiResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso[], string> listaCommessi(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/listaCommessi", ReplyAction="http://tempuri.org/Iadmin/listaCommessiResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso[], string>> listaCommessiAsync(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/listaProdotti", ReplyAction="http://tempuri.org/Iadmin/listaProdottiResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto[], string> listaProdotti(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/listaProdotti", ReplyAction="http://tempuri.org/Iadmin/listaProdottiResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto[], string>> listaProdottiAsync(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/listaTransazioni", ReplyAction="http://tempuri.org/Iadmin/listaTransazioniResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione[], string> listaTransazioni(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/listaTransazioni", ReplyAction="http://tempuri.org/Iadmin/listaTransazioniResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione[], string>> listaTransazioniAsync(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/modificaUtente", ReplyAction="http://tempuri.org/Iadmin/modificaUtenteResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente, string> modificaUtente(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/modificaUtente", ReplyAction="http://tempuri.org/Iadmin/modificaUtenteResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente, string>> modificaUtenteAsync(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/eliminaUtente", ReplyAction="http://tempuri.org/Iadmin/eliminaUtenteResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, string> eliminaUtente(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/eliminaUtente", ReplyAction="http://tempuri.org/Iadmin/eliminaUtenteResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, string>> eliminaUtenteAsync(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/aggiungiUtente", ReplyAction="http://tempuri.org/Iadmin/aggiungiUtenteResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente, string> aggiungiUtente(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/aggiungiUtente", ReplyAction="http://tempuri.org/Iadmin/aggiungiUtenteResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente, string>> aggiungiUtenteAsync(Sito.ServiceReference2.Utente ut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/modificaCommesso", ReplyAction="http://tempuri.org/Iadmin/modificaCommessoResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso, string> modificaCommesso(Sito.ServiceReference2.Commesso comm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/modificaCommesso", ReplyAction="http://tempuri.org/Iadmin/modificaCommessoResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso, string>> modificaCommessoAsync(Sito.ServiceReference2.Commesso comm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/eliminaCommesso", ReplyAction="http://tempuri.org/Iadmin/eliminaCommessoResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, string> eliminaCommesso(Sito.ServiceReference2.Commesso comm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/eliminaCommesso", ReplyAction="http://tempuri.org/Iadmin/eliminaCommessoResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, string>> eliminaCommessoAsync(Sito.ServiceReference2.Commesso comm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/aggiungiCommesso", ReplyAction="http://tempuri.org/Iadmin/aggiungiCommessoResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso, string> aggiungiCommesso(Sito.ServiceReference2.Commesso comm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/aggiungiCommesso", ReplyAction="http://tempuri.org/Iadmin/aggiungiCommessoResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso, string>> aggiungiCommessoAsync(Sito.ServiceReference2.Commesso comm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/modificaProdotto", ReplyAction="http://tempuri.org/Iadmin/modificaProdottoResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto, string> modificaProdotto(Sito.ServiceReference2.Prodotto prd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/modificaProdotto", ReplyAction="http://tempuri.org/Iadmin/modificaProdottoResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto, string>> modificaProdottoAsync(Sito.ServiceReference2.Prodotto prd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/eliminaProdotto", ReplyAction="http://tempuri.org/Iadmin/eliminaProdottoResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, string> eliminaProdotto(Sito.ServiceReference2.Prodotto prd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/eliminaProdotto", ReplyAction="http://tempuri.org/Iadmin/eliminaProdottoResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, string>> eliminaProdottoAsync(Sito.ServiceReference2.Prodotto prd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/aggiungiProdotto", ReplyAction="http://tempuri.org/Iadmin/aggiungiProdottoResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto, string> aggiungiProdotto(Sito.ServiceReference2.Prodotto prd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/aggiungiProdotto", ReplyAction="http://tempuri.org/Iadmin/aggiungiProdottoResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto, string>> aggiungiProdottoAsync(Sito.ServiceReference2.Prodotto prd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/modificaTransazione", ReplyAction="http://tempuri.org/Iadmin/modificaTransazioneResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione, string> modificaTransazione(Sito.ServiceReference2.Transazione trn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/modificaTransazione", ReplyAction="http://tempuri.org/Iadmin/modificaTransazioneResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione, string>> modificaTransazioneAsync(Sito.ServiceReference2.Transazione trn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/eliminaTransazione", ReplyAction="http://tempuri.org/Iadmin/eliminaTransazioneResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, string> eliminaTransazione(Sito.ServiceReference2.Transazione trn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/eliminaTransazione", ReplyAction="http://tempuri.org/Iadmin/eliminaTransazioneResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, string>> eliminaTransazioneAsync(Sito.ServiceReference2.Transazione trn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/aggiungiTransazione", ReplyAction="http://tempuri.org/Iadmin/aggiungiTransazioneResponse")]
        System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione, string> aggiungiTransazione(Sito.ServiceReference2.Transazione trn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iadmin/aggiungiTransazione", ReplyAction="http://tempuri.org/Iadmin/aggiungiTransazioneResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione, string>> aggiungiTransazioneAsync(Sito.ServiceReference2.Transazione trn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IadminChannel : Sito.ServiceReference2.Iadmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IadminClient : System.ServiceModel.ClientBase<Sito.ServiceReference2.Iadmin>, Sito.ServiceReference2.Iadmin {
        
        public IadminClient() {
        }
        
        public IadminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IadminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IadminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IadminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente[], string> listaUtenti(Sito.ServiceReference2.Utente ut) {
            return base.Channel.listaUtenti(ut);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente[], string>> listaUtentiAsync(Sito.ServiceReference2.Utente ut) {
            return base.Channel.listaUtentiAsync(ut);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso[], string> listaCommessi(Sito.ServiceReference2.Utente ut) {
            return base.Channel.listaCommessi(ut);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso[], string>> listaCommessiAsync(Sito.ServiceReference2.Utente ut) {
            return base.Channel.listaCommessiAsync(ut);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto[], string> listaProdotti(Sito.ServiceReference2.Utente ut) {
            return base.Channel.listaProdotti(ut);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto[], string>> listaProdottiAsync(Sito.ServiceReference2.Utente ut) {
            return base.Channel.listaProdottiAsync(ut);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione[], string> listaTransazioni(Sito.ServiceReference2.Utente ut) {
            return base.Channel.listaTransazioni(ut);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione[], string>> listaTransazioniAsync(Sito.ServiceReference2.Utente ut) {
            return base.Channel.listaTransazioniAsync(ut);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente, string> modificaUtente(Sito.ServiceReference2.Utente ut) {
            return base.Channel.modificaUtente(ut);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente, string>> modificaUtenteAsync(Sito.ServiceReference2.Utente ut) {
            return base.Channel.modificaUtenteAsync(ut);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, string> eliminaUtente(Sito.ServiceReference2.Utente ut) {
            return base.Channel.eliminaUtente(ut);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, string>> eliminaUtenteAsync(Sito.ServiceReference2.Utente ut) {
            return base.Channel.eliminaUtenteAsync(ut);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente, string> aggiungiUtente(Sito.ServiceReference2.Utente ut) {
            return base.Channel.aggiungiUtente(ut);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Utente, string>> aggiungiUtenteAsync(Sito.ServiceReference2.Utente ut) {
            return base.Channel.aggiungiUtenteAsync(ut);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso, string> modificaCommesso(Sito.ServiceReference2.Commesso comm) {
            return base.Channel.modificaCommesso(comm);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso, string>> modificaCommessoAsync(Sito.ServiceReference2.Commesso comm) {
            return base.Channel.modificaCommessoAsync(comm);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, string> eliminaCommesso(Sito.ServiceReference2.Commesso comm) {
            return base.Channel.eliminaCommesso(comm);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, string>> eliminaCommessoAsync(Sito.ServiceReference2.Commesso comm) {
            return base.Channel.eliminaCommessoAsync(comm);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso, string> aggiungiCommesso(Sito.ServiceReference2.Commesso comm) {
            return base.Channel.aggiungiCommesso(comm);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Commesso, string>> aggiungiCommessoAsync(Sito.ServiceReference2.Commesso comm) {
            return base.Channel.aggiungiCommessoAsync(comm);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto, string> modificaProdotto(Sito.ServiceReference2.Prodotto prd) {
            return base.Channel.modificaProdotto(prd);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto, string>> modificaProdottoAsync(Sito.ServiceReference2.Prodotto prd) {
            return base.Channel.modificaProdottoAsync(prd);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, string> eliminaProdotto(Sito.ServiceReference2.Prodotto prd) {
            return base.Channel.eliminaProdotto(prd);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, string>> eliminaProdottoAsync(Sito.ServiceReference2.Prodotto prd) {
            return base.Channel.eliminaProdottoAsync(prd);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto, string> aggiungiProdotto(Sito.ServiceReference2.Prodotto prd) {
            return base.Channel.aggiungiProdotto(prd);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Prodotto, string>> aggiungiProdottoAsync(Sito.ServiceReference2.Prodotto prd) {
            return base.Channel.aggiungiProdottoAsync(prd);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione, string> modificaTransazione(Sito.ServiceReference2.Transazione trn) {
            return base.Channel.modificaTransazione(trn);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione, string>> modificaTransazioneAsync(Sito.ServiceReference2.Transazione trn) {
            return base.Channel.modificaTransazioneAsync(trn);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, string> eliminaTransazione(Sito.ServiceReference2.Transazione trn) {
            return base.Channel.eliminaTransazione(trn);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, string>> eliminaTransazioneAsync(Sito.ServiceReference2.Transazione trn) {
            return base.Channel.eliminaTransazioneAsync(trn);
        }
        
        public System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione, string> aggiungiTransazione(Sito.ServiceReference2.Transazione trn) {
            return base.Channel.aggiungiTransazione(trn);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<Sito.ServiceReference2.adminEsito, Sito.ServiceReference2.Transazione, string>> aggiungiTransazioneAsync(Sito.ServiceReference2.Transazione trn) {
            return base.Channel.aggiungiTransazioneAsync(trn);
        }
    }
}
